name: snapsign
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi==0.135.1
      - uvicorn==0.41.0
      - sqlalchemy==2.0.48
      - pymysql==1.1.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.13.1
      - starlette==0.52.1
      - python-dotenv==1.2.2
      - python-multipart==0.0.22
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - click==8.3.1
      - colorama==0.4.6
      - greenlet==3.3.2
      - h11==0.16.0
      - idna==3.11
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
